# Generated by Django 4.0.2 on 2022-05-11 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doct_name', models.CharField(max_length=100)),
                ('doct_specialization', models.CharField(max_length=250)),
                ('doct_image', models.ImageField(upload_to='doctors')),
                ('doct_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
    ]
